#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_CocosRVO_proto;
extern se::Class* __jsb_CocosRVO_class;

bool js_register_CocosRVO(se::Object* obj);
bool register_all_RVO(se::Object* obj);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentVelocity);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentRadius);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentPrefVelocity);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setTimeStep);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getNextObstacleVertexNo);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentDefaults);
SE_DECLARE_FUNC(js_RVO_CocosRVO_updateVisualization);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getNumObstacleVertices);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentTimeHorizon);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getTimeStep);
SE_DECLARE_FUNC(js_RVO_CocosRVO_doStep);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentMaxNeighbors);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentTimeHorizon);
SE_DECLARE_FUNC(js_RVO_CocosRVO_addObstacle);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentNumAgentNeighbors);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentRadius);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentVelocity);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentsNextPos);
SE_DECLARE_FUNC(js_RVO_CocosRVO_removeAgent);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentNumORCALines);
SE_DECLARE_FUNC(js_RVO_CocosRVO_reachedGoal);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentNeighborDist);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentMaxSpeed);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentPrefVelocity);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setPreferredVelocities);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentMaxNeighbors);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getNumAgents);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentMaxSpeed);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentTimeHorizonObst);
SE_DECLARE_FUNC(js_RVO_CocosRVO_addAgent);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentObstacleNeighbor);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getGlobalTime);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getObstacleVertex);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentAgentNeighbor);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentPosition);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentTimeHorizonObst);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentNumObstacleNeighbors);
SE_DECLARE_FUNC(js_RVO_CocosRVO_queryVisibility);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentPosition);
SE_DECLARE_FUNC(js_RVO_CocosRVO_processObstacles);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getPrevObstacleVertexNo);
SE_DECLARE_FUNC(js_RVO_CocosRVO_release);
SE_DECLARE_FUNC(js_RVO_CocosRVO_setAgentNeighborDist);
SE_DECLARE_FUNC(js_RVO_CocosRVO_getAgentORCALine);
SE_DECLARE_FUNC(js_RVO_CocosRVO_create);

